//AUTH
export const USER_LOADED='USER_LOADED'
export const LOADING_ACTION='LOADING_ACTION'
export const AUTH_ERROR='AUTH_ERROR'
export const REGISTER_SUCCESS='REGISTER_SUCCESS'
export const LOGIN_SUCCESS='LOGIN_SUCCESS'
export const LOGOUT_SUCCESS='LOGOUT_SUCCESS'
//ARTICLES
export const LOADING_ARTICLES='LOADING_ARTICLES'
export const GET_ARTICLES='GET_ARTICLES'
export const ADD_ARTICLE='ADD_ARTICLE'
export const UPDATE_ARTICLE='UPDATE_ARTICLE'
export const DELETE_ARTICLE='DELETE_ARTICLE'
export const LIKE_ARTICLE='LIKE_ARTICLE'
export const DISLIKE_ARTICLE='DISLIKE_ARTICLE'
//CATEGORIES
export const GET_CATEGORIES='GET_CATEGORIES'
//PROFILE
export const EDIT_USER='EDIT_USER'
export const LOADING_EDIT_USER='LOADING_EDIT_USER'
//NOTIFICATION
export const GET_NOTIFS='GET_NOTIFS'
export const DELETE_NOTIF='DELETE_NOTIF'
export const LOADING_NOTIF='LOADING_NOTIF'
//MESSAGES
export const GET_MESSAGES='GET_MESSAGES'
export const LOADING_MESSAGES='LOADING_MESSAGES'
export const SEND_MESSAGE='SEND_MESSAGE'
//COMPLAINTS
export const GET_COMPLAINTS='GET_COMPLAINTS'
export const ADD_COMPLAINTS='ADD_COMPLAINTS'
export const LOADING_COMPLAINTS='LOADING_COMPLAINTS'
export const EDIT_COMPLAINT='EDIT_COMPLAINT'
export const DELETE_COMPLAINT='DELETE_COMPLAINT'
export const RESOLVE_COMPLAINT='RESOLVE_COMPLAINT'
//COMMENT
export const GET_COMMENTS='GET_COMMENTS'
export const ADD_COMMENT='ADD_COMMENT'
export const EDIT_COMMENT='UPDATE_COMMENT'
export const DELETE_COMMENT='DELETE_COMMENT'
export const LOADING_COMMENTS='LOADING_COMMENTS'
//CALENDAR
export const GET_EVENTS='GET_EVENTS'
export const LOADING_EVENTS='LOADING_EVENTS'